# Enable mouse emulation.
# CONFIG_ZMK_POINTING=y

# Change idle settings
# CONFIG_ZMK_IDLE_TIMEOUT=30000

# Deep sleep settings
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Custom keyboard name (max. 16 characters)
# CONFIG_ZMK_KEYBOARD_NAME="My Keyboard"

# My additions
CONFIG_BT_SMP_ALLOW_UNAUTH_OVERWRITE=y
CONFIG_BT_KEYS_OVERWRITE_OLDEST=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
